spring.application.name=loan-application-service

server.port=3333

# ---------- Default Data Source (MySQL for Student) ----------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/home_loan_loan_application
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#logging.level.root=info
#logging.level.com..rest=info
#logging.level.com.example.enquiry.serviceimpl=debug